### ISSUE TITLE
Drupal 8 core not updating within container

### ISSUE THREAD

**Issue by djac** [dcycle/docker-drupal#16]
I'm using an older version of starterkit-drupal8site and Drupal 8.8.5.

Composer was used to update to Drupal 8.9.16, however the Docker container still appears to be running 8.8.5.

I tried removing the Docker volumes (`docker-compose down -v`) and running deploy.sh from scratch, however Drupal is still on 8.8.5.

After pushing the core update to Pantheon, I can confirm core is up to date in the Pantheon environment (8.9.16).

Any help would be appreciated, thanks!

**Comment by alberto56** [comment]
@djac please provide the base image used in your Dockerfile. Is it:

    FROM dcycle/drupal:8drush

?

**Comment by djac** [comment]
@alberto56 yes, that's the correct base image!

**Comment by alberto56** [comment]
When I run:

    docker run --rm --entrypoint /bin/bash dcycle/drupal:8drush -c 'drush status'

I get Drupal version : 8.9.16

Meaning that is the version of Drupal on the image. (It is automatically updated Wednesdays)

Please make sure you are pulling the latest version of the image (i.e. docker pull dcycle/drupal:8drush)

If the problem persists, I suspect that in your docker-compose.yml file you might be sharing the entire Drupal, with a line such as:

```
  drupal:
    ...
    volumes:
      - ".:/var/www/html"

```
If such is the case, you are basically ignoring the version of Drupal on the image, and using your own code instead.

You are therefore not taking advantage of the fact that dcycle/drupal:8drush is automatically updated every Wednesday.

You mentioned updating with composer. Unless your dockercompose.yml shares your local directory with /var/www/html, You should normally never need to do this, because the base image is rebuilt with the latest version of Drupal Wednesdays.

Nonetheless, if you _are_ sharing the entire Drupal root between your local computer and the docker container, updating via composer _should_ update your local code.

Please share (1) your docker-compose.yml file(s) and (2) the exact commands you have used to update Drupal with Composer.

**Comment by djac** [comment]
@alberto56 you nailed it! The base image was out of date.

1. `docker pull dcycle/drupal:8drush` updated the base image. `drush status` as per your comment was now showing 8.9.16!
2. My dev environment was still not up to date however, and deploy.sh was failing:
`Cannot start service drupal: error while creating mount source path '/host_mnt/Users/djac/code/contrax-composer/docker/scripts': mkdir /host_mnt/Users/djac/code/contrax-composer/docker/scripts: no such file or directory`
3. I simply rebooted my machine and ran deploy.sh again, now everything is working as expected

I now see the root of the issue. In deploy.sh I had:
`docker pull dcycle/drupal:8drush9`
Instead of:
`docker pull dcycle/drupal:8drush`

Sorry for the bother and thanks so much for your help!
