### ISSUE TITLE
Upgrade to php 8.1 or 8.2

### ISSUE THREAD

**Issue by belambic** [dcycle/docker-drupal#38]
PHP 8.0 is reaching EOL on 26th November 2023, so it would be nice to get the image upgraded.

I've installed our environment on a test EC2 instance running debian and PHP 8.2 and everything looks good so far, but I haven't done a full test of all our contrib modules yet.

Also it seems like php-mcrypt has been brought back into the fold maybe, because I was able to do a regular install of the module instead of jumping through the pecl/pear hoops we had to do before.

**Comment by alberto56** [comment]
Here is a pull request which uses version 8.1 of [the community Drupal image](https://hub.docker.com/layers/library/drupal/7-php8.1/images/sha256-c50f412279cebfb2ffab3347b589b527134684a2fa169148adc4d0d514af1e8b?context=explore) as a base.

If tests pass this should be good to go!

I prefer 8.1 at this point for Drupal 7, and even Drupal 10, because PHP 8.2 introduced a deprecation notice for classes which use properties which are not explicitly defined; and a quick glance at several contrib modules shows that many have not included this change yet.

**Comment by alberto56** [comment]
Tests are passing at https://github.com/dcycle/docker-drupal/pull/39

I will merge and report back when the image with PHP 8.1 is published.

**Comment by alberto56** [comment]
This now works at:

    docker pull dcycle/drupal:7php8 && docker run --rm dcycle/drupal:7php8 /bin/bash -c 'php -v'
    ...
    PHP 8.1.25 (cli) (built: Oct 28 2023 02:32:47) (NTS)

**Comment by belambic** [comment]
Thanks Albert, this seems to be working well, we're testing it alongside an 8.2 ec instance and both are fine so far
